language: objective-c

xcode_project: SwipyCell.xcodeproj
xcode_scheme: SwipyCell
osx_image: xcode11.1
xcode_sdk: iphonesimulator13.1

branches:
  except:
    - develop

before_install:
  - gem update cocoapods
  - gem install xcpretty --quiet

script:
- xcodebuild -project SwipyCell.xcodeproj -scheme SwipyCell -sdk iphonesimulator clean build | xcpretty
- pod lib lint
